### PR TITLE
FastMapInt - over 5 times faster than existing map & fixes rounding issue going below 0

### PR DESCRIPTION
**Pull request by brewmanz**
Ver1 (intermediate & obsolete) fixes the rounding issue but slightly than existing map. If you wish to tidy up, the conditional preprocessor directives for VER1 can be removed. 
Ver2 (active) all of Ver1 fixes and speeds up map significantly by removing the divide operation. 
Additional example sketches: 
fastMapIntegerArithmeticTest - test some new helper functions used by FastMapInt. 
fastMapIntTest - verify correct operation of new FastMapInt class. 
fastMapIntSpeed - demonstrate faster FastMapInt map function. 
Sorry for the delay. I had a bit of a disaster when I thoughtlessly installed latest FastMap library, wiping my changes including the local git repository! 
Overall it's been quite fun.

### CODE REVIEW

**Comment by RobTillaart** [comment]
Thanks,

just had a quick test - AVR UNO factor 5.8  impressive  (warnings in compilation)

Tried to compile it on ESP2 but it failed on 

```
D:\Rob\WORK\Arduino\libraries\FastMap-FastMapInt\FastMap.cpp: In function 'int MultiplyByFixedPointFraction(int, long int, bool)':

D:\Rob\WORK\Arduino\libraries\FastMap-FastMapInt\FastMap.cpp:159:88: error: default argument given for parameter 3 of 'int MultiplyByFixedPointFraction(int, long int, bool)' [-fpermissive]

 int MultiplyByFixedPointFraction(int factor, long fixedPointFraction, bool bDebug=false){

                                                                                        ^

In file included from D:\Rob\WORK\Arduino\libraries\FastMap-FastMapInt\FastMap.cpp:27:0:

D:\Rob\WORK\Arduino\libraries\FastMap-FastMapInt\FastMap.h:61:5: note: previous specification in 'int MultiplyByFixedPointFraction(int, long int, bool)' here

 int MultiplyByFixedPointFraction(int factor, long fixedPointFraction, bool bDebug=false);

     ^

D:\Rob\WORK\Arduino\libraries\FastMap-FastMapInt\FastMap.cpp: In function 'int MultiplyByFixedPointFraction(int, long int, bool)':

D:\Rob\WORK\Arduino\libraries\FastMap-FastMapInt\FastMap.cpp:161:8: warning: unused variable 'bFacNeg' [-Wunused-variable]

   bool bFacNeg = factor < 0;

        ^

Using library FastMap-FastMapInt at version 0.3.1 in folder: D:\Rob\WORK\Arduino\libraries\FastMap-FastMapInt 
exit status 1
Error compiling for board ESP32 Dev Module.

```

For code size it might be better to use a # define DEBUG_FM flag instead of using a parameter
Think that would solve the compile issue also

Did not investigate the working to see if the unused var bFacNeg should be used or removed. 
To be continued coming week.

**Comment by RobTillaart** [comment]
PS< the ESP32 has no build in LED so I had to comment that in the sketch.

**Comment by RobTillaart** [comment]
Just had another look, **FastMapInt** does not work for **32 bit** integers. 
It is incorrect to compare the performance to the default **map()** function that does all math 32 bit. 

I'll rewrite the example to check what the gain would be compared to an int version of **map().**

**Comment by RobTillaart** [comment]
Worst case on ESP32
```
imap
  10000 calls, uS=1648
  final x=319

map
  10000 calls, uS=1808
  final x=319

 Speed-up Ratio:	0.912
```

Best case on ESP32
```
imap
  10000 calls, uS=268
  final x=31

map
  10000 calls, uS=293
  final x=31

 Speed-up Ratio:	0.915
```
So on ESP32 it apparently doesn't matter (always 32 bit)  ==> that implies we can simplify imap for ESP32
```cpp
int imap(int x, int inmin, int inmax, int outmin, int outmax)
{
  long a = (x - inmin);
  a *= (outmax - outmin);
  int c = (inmax - inmin);
  #if defined (ESP32)
  return outmin + int(a / c); 
  #else
  if (a > 32767 ) return outmin + int(a / c);  // if a > 16 bit do 32 bit math.
  if (a <-32767 ) return outmin + int(a / c);  // if a > 16 bit do 32 bit math.
  return outmin + int(a) / c;                  // do 16 bit math if possible
  #endif
}

resulting in 
```
imap
  10000 calls, uS=165
  final x=31

map
  10000 calls, uS=293
  final x=31

 Speed-up Ratio:	0.563
```

A test with FastMapInt versus original map()

```
Original map
  10000 calls, uS=2231
  final x=249

FastMapInt::map
  10000 calls, uS=2653
  final x=249

 Speed-up Ratio:	0.841
```
even slower....

**Comment by brewmanz** [comment]
A) Wow; you must have a few different Arduinos to play with! 
I just have Mega and Nano ones, and a month ago I had never touched an Arduino. I didn't realise that they used anything but 16-bit for int (non-16-bit int will have caused my 'sanity tests' to fail anyway). Maybe I should have guessed, as the SImuino(?) under Linux used 32-bit int, but I stopped using that when my Arduino clones arrived. 
B) I have a special interest in Integer mathematics, and will look at the issues you have raised. I'm sure that my fixed point no-divide division algorithm can speed up even 32-bit int (using 32.32 rather than 16.16), unless the CPU has hardware integer divide. 
C) The reason for my interest in this is that I want to create a high precision (0.01%[*]) DAC generating relatively pure audio sine waves but the sine function takes around 117 uS which is way too slow. Yes, I know I could add an external signal generator for a few dollars but I would rather spend dozens of hours writing software; it's what I do. So I want to write a fast 14-bit sine function which will require table lookup and interpolation - classic use of map, but existing one has glitch around 0 (could fix via offsetting) and is too slow. Hence my main interest is in speeding up 16-bit maths. 
[*] I am aware that I need to take the digital pin impedance into account to achieve this. Fortunately there is just c. 5 ohm measured difference between HIGH and LOW states (25 Ω & 20 Ω).

**Comment by RobTillaart** [comment]
A) up to 10 different? But uno/nano amd esp32 are mostly used.

B) division can also be optimized by a multiply + shift  operation. Calculating the correct numbers takes time and depend on input range. 

C) i have worked on that in 2011. My isin() is about 40-50 us per calll and accuracy might be what you need. In fact it is part of a library to be published soon. Itan() is under investigatio

**Comment by brewmanz** [comment]
I am having difficulty finding information on ESP32; it doesn't appear on [https://www.arduino.cc/en/Main/Products](url) or [https://www.arduino.cc/en/Products/Compare](url). What macros/#defines can be used to determine that the processor has 32-bit int?

**Comment by RobTillaart** [comment]
Esp32 is not described at arduino 
It is from a company called espressif 

Every processor (almost) support 32 bit int.
Your question should be how to determine a processor has 32bit registers. Think you need to do some math and check timing, but that us runtime.

I am not aware of compile time macros that indicate it directly. But there are always  
If defined __AVR__. ESP32 etc. Need to look up the details.

**Comment by RobTillaart** [comment]
2007 - https://www.codeproject.com/Articles/17480/Optimizing-integer-divisions-with-Multiply-Shift-i

**Comment by RobTillaart** [comment]
> I am having difficulty finding information on ESP32; 

https://randomnerdtutorials.com/getting-started-with-esp32/

**Comment by RobTillaart** [comment]
FYI - published my fast sin as a library. https://github.com/RobTillaart/FastTrig
work on itan() is in progress and results on ESP32 go in the right direction.
(AVR will follow)

**Comment by brewmanz** [comment]
**General**
- I have created FastMapLong as sibling to FastMapInt. 
- Refactored the code to no longer assume 16-bit int. 
- Confident it works with 16 & 32-bit int and long. Should also work with 8-bit int.
- Considered adding 24-bit numbers but demurred. 
- Works with 64-bit int/long PROVIDED THAT numbers themselves are limited to 32-bit sizes. This limitation is because I couldn't find 128-bit numbers in the compiler. This is because, whilst 32-bit uses 64-bit (32.32 fixed point) intermediate, I could only compile 64-bit also with 32.32 fixed point intermediate. 
- Improved static optimisation e.g. mapping 1024 to 256 is simplified to 4 to 1, 48 to 36 is simplified to 4 to 3 (I hope; not actually tested). This reduces bits used in calculations. 
- Added dynamic optimisation, to use shorter numbers where possible. 
- As I don't have a 32-bit device, I can't test that side, but it's pretty quick on the 16-bit devices (Nano). 

**Examples/Tests**
- There are several new Test example sketches, as they are too large to load into Nano. 

**fastMapIntSpeed**
- dynamically calculates displayed loop count. 
- sundry tweaks inside e.g. grabbing back info (calcInfo) on how result was calculated; this verified dynamic optimisation. 
- as well as comparing original map with FastMapInt, now also compares with FastMapLong. 

Results are:
```
Original map(long)
  10000 calls, uS=404788
  final x=249

fastMapInt::map
  10000 calls, uS=114936
  final x=249

fastMapLong::map
  10000 calls, uS=142096
  final x=249

 Speed-up Ratio (Int):	3.522
 Speed-up Ratio (Long):	2.849
```

**Comment by RobTillaart** [comment]
I've seen your update but no time to dive into it. 
Later.

**Comment by brewmanz** [comment]
I have found some rounding anomalies with my 'optimising' code; I've clearly taken too many shortcuts! 
Sometimes the result is out-by-one (like existing `map` as it crosses zero). 
Not quite 'back to the drawing board' but I need to look into it.

**Comment by brewmanz** [comment]
Not quite as fast, as had to allow more bits of precision. Then again, no known issues with out-by-one arithmetic now, either.

**Comment by RobTillaart** [comment]
> Not quite as fast, as had to allow more bits of precision. Then again, no known issues with out-by-one arithmetic now, either.

It becomes quite a big exercise, quite a determination (is steadfastness a better word?)
do you have some time measurements?

**Comment by brewmanz** [comment]
Speed-up it about twice as fast (had to add extra bits to address rounding issues):
13:35:34.924 -> Oct 14 2020 @ 13:35:06
13:35:34.924 -> /home/bryan/git/FastMap/examples/fastMapIntSpeed/fastMapIntSpeed.ino
13:35:34.924 -> lib version: 0.3.1
13:35:34.924 -> 
13:35:35.355 -> Original map(long)
13:35:35.355 ->   10000 calls, uS=404792
13:35:35.355 ->   final x=249
13:35:35.355 -> 
13:35:35.554 -> fastMapInt::map
13:35:35.554 ->   10000 calls, uS=196604
13:35:35.554 ->   final x=249
13:35:35.554 -> 
13:35:35.752 -> fastMapLong::map
13:35:35.752 ->   10000 calls, uS=212632
13:35:35.752 ->   final x=249
13:35:35.752 -> 
13:35:35.752 ->  Speed-up Ratio (Int):	2.059
13:35:35.785 ->  Speed-up Ratio (Long):	1.904
13:35:35.785 -> 
13:35:35.785 -> 
13:35:35.785 -> ...Done

**Comment by RobTillaart** [comment]
Came across this open PR, and decided not to include it into the library.
I will add a link in the readme.md to this PR so people can easily find it if they are interested. 

Anyway thanks for your efforts, thinking and contributions!

**Pull request closed without merging**
